name: SimpleDash
version: 1.5
author: CinturonCris
main: c.cris.SimpleDash.SimpleDash
api-version: 1.17
commands:
  simpledash:
    description: Reload the SimpleDash plugin configurations
    usage: /simpledash reload
    permission: simpledash.reload
permissions:
  simpledash.use:
    description: Allows the player to use the dash functionality.
    default: true
  simpledash.reload:
    description: Allows the user to reload the SimpleDash plugin configuration
    default: op
softdepend: [ItemsAdder]
